"""The House's lived-in clutter layer (art #104, Q21 = A; docs/house.md "Clutter"): small props from the dressing
library's `clutter` class (and a few others) added to every interior room's dressing file as a generated block.

Pure Python and deterministic: one `random.Random` per room seeded with SEED and the room id; `house --clutter` writes
the block at the end of `layouts/house/dressing/<room>.toml` after MARK (everything after MARK is replaced; edit RULES
and HOSTS here, not the block). The layers, in room-local metres like the dressing:
- surface clutter on the tops of HOSTS furniture (not a station's own prop: stations stay readable), up to
  `per_host` items each, kept apart from what already stands on the top (a lamp, a computer);
- wall dressing (frames, shelves, clocks) on free wall spans: on a real wall face, clear of door openings, windows,
  corners, the stairs and anything in front of the wall at its height;
- floor clutter (baskets, shoes, toys) against free wall spans, clear of doors, stations, spawns and the stairs, and a
  doormat inside the room's first door.
Every clutter item is non-solid (`collision = "none"` in the library, or under 0.3 m tall), so the walk's capsule and
the overlap rule do not see it.
"""
from __future__ import annotations

import random
import tomllib
from pathlib import Path

from . import house_dressing as hd
from . import house_routes

SEED = 104
MARK = "# ---- clutter (art #104): generated by `house --clutter` (tools/runner/house_clutter.py); edit its RULES, not this block"
GAP = 0.04  # between two clutter items, and from a top's edge
WALL_H = {"picture_frame": 1.4, "wall_shelf": 1.45, "wall_clock": 1.85}  # the wall item's bottom above the floor
CORNER = 0.35  # no wall or floor item this close to a room corner
WINDOW_HALF = 1.15  # a window is 2 m wide: wall items keep this far from its centre
STAIR_GAP = 0.3

# host id -> the clutter its top carries
HOSTS = {
    "kitchen_counter": ("cup_set", "plate_stack", "bottles", "cooking_pot", "fruit_bowl"),
    "stove": ("cooking_pot",),
    "sideboard": ("vase_flowers", "bottles", "book_stack", "fruit_bowl"),
    "console_table": ("vase_flowers", "book_stack", "paper_stack"),
    "coffee_table": ("book_stack", "cup_set", "paper_stack", "fruit_bowl"),
    "desk": ("paper_stack", "book_stack", "cup_set"),
    "dresser": ("book_stack", "vase_flowers", "bottles"),
    "nightstand": ("book_stack", "cup_set"),
    "small_table": ("cup_set", "vase_flowers", "book_stack"),
    "tv_cabinet": ("book_row", "vase_flowers"),
    "filing_cabinet": ("paper_stack", "book_stack"),
    "toy_chest": ("toy_blocks",),
    "tray_table": ("paper_stack", "bottles"),
    "crate": ("bottles", "paper_stack", "book_stack"),
    "cardboard_box": ("paper_stack", "book_stack"),
    "landing_bench": ("book_stack", "basket"),
    "shoe_rack": ("shoes",),
    "meat_freezer": ("paper_stack", "bottles"),
}

# room -> wall items (in order of placement), floor items, surface items at most per host and per room
RULES = {
    # the ground floor
    "kitchen": {"wall": ("wall_clock", "wall_shelf", "picture_frame", "picture_frame"), "floor": ("basket",)},
    "hallway": {"wall": ("picture_frame", "picture_frame", "wall_shelf", "wall_clock", "picture_frame"),
                "floor": ("doormat", "shoes", "shoes", "basket")},
    "living_room": {"wall": ("picture_frame", "wall_shelf", "picture_frame", "wall_clock", "picture_frame"),
                    "floor": ("basket", "book_stack", "toy_blocks")},
    "dining_room": {"wall": ("picture_frame", "wall_clock", "picture_frame", "wall_shelf"), "floor": ("basket",)},
    "stairs": {"wall": ("picture_frame", "picture_frame", "picture_frame"), "floor": ("shoes",)},
    "pantry": {"wall": ("wall_shelf", "wall_shelf"), "floor": ("basket", "bottles", "basket")},
    "wc": {"wall": ("picture_frame", "wall_shelf"), "floor": ("basket",)},
    # the upper floor
    "bedroom": {"wall": ("picture_frame", "picture_frame", "wall_shelf", "wall_clock"),
                "floor": ("shoes", "basket", "book_stack")},
    "kids_room": {"wall": ("picture_frame", "wall_shelf", "picture_frame", "wall_clock"),
                  "floor": ("toy_blocks", "toy_blocks", "book_stack", "basket", "shoes")},
    "landing": {"wall": ("picture_frame", "picture_frame", "wall_shelf", "picture_frame"), "floor": ("basket",)},
    "study": {"wall": ("wall_shelf", "wall_clock", "picture_frame", "wall_shelf"),
              "floor": ("book_stack", "book_stack", "paper_stack", "basket")},
    "bathroom": {"wall": ("wall_shelf", "picture_frame", "wall_shelf"), "floor": ("basket",)},
    "guest_room": {"wall": ("picture_frame", "wall_shelf", "picture_frame", "wall_clock"),
                   "floor": ("shoes", "basket", "book_stack")},
    # the basement
    "storage": {"wall": ("wall_shelf", "wall_shelf", "wall_clock"), "floor": ("basket", "bottles", "paper_stack")},
    "darkroom": {"wall": ("wall_shelf", "wall_shelf", "picture_frame"), "floor": ("paper_stack", "bottles")},
    "corridor": {"wall": ("wall_clock", "picture_frame"), "floor": ("basket",)},
    "boiler_room": {"wall": ("wall_shelf", "wall_clock"), "floor": ("bottles", "basket")},
    # the hall's sight lines from the passage run at eye height (house_basement.hall_sight): only clocks above them
    "generator_hall": {"wall": ("wall_clock", "wall_clock"), "floor": ("bottles", "paper_stack", "basket")},
    "pump_room": {"wall": ("wall_shelf", "wall_clock"), "floor": ("bottles", "basket")},
    "switch_room": {"wall": ("wall_clock", "wall_shelf"), "floor": ("paper_stack", "bottles")},
    "passage": {"wall": ("wall_clock",), "floor": ("basket",)},
}
PER_HOST = 4
PER_ROOM = 16  # surface items at most per room
SIDE_FACE = {"N": "S", "S": "N", "W": "E", "E": "W"}  # an item against this wall looks into the room


def strip(text: str) -> str:
    """The dressing file's text without its generated block."""
    i = text.find(MARK)
    return text if i < 0 else text[:i].rstrip() + "\n"


def _box(kind: str, at, face: str, cat: dict) -> dict:
    r = hd.resolve({"id": kind, "at": list(at), "face": face}, cat)
    r["fp"] = hd.footprint(r)
    return r


def _ov(a, b, gap=0.0) -> bool:
    return a[0] < b[2] + gap and b[0] < a[2] + gap and a[1] < b[3] + gap and b[1] < a[3] + gap


def _side_of(at, w: float, d: float):
    x, z = at
    if abs(z) < 1e-6 and 0 < x < w:
        return "N", x
    if abs(z - d) < 1e-6 and 0 < x < w:
        return "S", x
    if abs(x) < 1e-6 and 0 < z < d:
        return "W", z
    if abs(x - w) < 1e-6 and 0 < z < d:
        return "E", z
    return None, None


def wall_spans(sh: dict) -> dict:
    """side -> merged [a, b] spans along it where the shell has a wall (doors already cut)."""
    w, d, t = sh["w"], sh["d"], hd.WALL_T
    out: dict = {s: [] for s in "NSWE"}
    for x0, z0, x1, z1 in sh["walls"]:
        if abs(z1 - z0 - 2 * t) < 1e-6 and x0 > -0.05:
            out["N" if abs(z0 + t) < 1e-6 else "S"].append([x0, x1])
        elif abs(x1 - x0 - 2 * t) < 1e-6 and z0 > -0.05:
            out["W" if abs(x0 + t) < 1e-6 else "E"].append([z0, z1])
    for s, spans in out.items():
        spans.sort()
        merged: list = []
        for a, b in spans:
            if merged and a <= merged[-1][1] + 1e-6:
                merged[-1][1] = max(merged[-1][1], b)
            else:
                merged.append([a, b])
        length = w if s in "NS" else d
        out[s] = [[max(a, CORNER), min(b, length - CORNER)] for a, b in merged if min(b, length - CORNER) > max(a, CORNER)]
    return out


def _strip_box(side: str, depth: float, w: float, d: float):
    t = hd.WALL_T
    return {"N": (0, t, w, t + depth), "S": (0, d - t - depth, w, d - t),
            "W": (t, 0, t + depth, d), "E": (w - t - depth, 0, w - t, d)}[side]


def _cut(spans: list, a: float, b: float) -> list:
    return [q for s0, s1 in spans for q in ((s0, min(s1, a)), (max(s0, b), s1)) if q[1] - q[0] > 1e-6]


def free_spans(sh: dict, side: str, depth: float, blocks: list) -> list:
    """The wall's spans on a side minus the projections of the blocker boxes that reach into its strip."""
    sb = _strip_box(side, depth, sh["w"], sh["d"])
    spans = [tuple(s) for s in wall_spans(sh)[side]]
    for b in blocks:
        if _ov(sb, b):
            spans = _cut(spans, b[0], b[2]) if side in "NS" else _cut(spans, b[1], b[3])
    return spans


def _place_along(sh: dict, side: str, kind: str, length: float, depth: float, h: float, spans: list, rng, cat):
    """Puts one item in the widest span that fits it (ties broken by rng); returns (item, spans left) or None."""
    fits = [s for s in spans if s[1] - s[0] >= length + 2 * GAP]
    if not fits:
        return None
    best = max(s[1] - s[0] for s in fits)
    pick = rng.choice([s for s in fits if s[1] - s[0] > best - 0.5])
    c = round((pick[0] + pick[1]) / 2, 2)
    w, d, t = sh["w"], sh["d"], hd.WALL_T
    off = t + depth
    at = {"N": (c, h, off), "S": (c, h, d - off), "W": (off, h, c), "E": (w - off, h, c)}[side]
    item = {"id": kind, "at": [round(v, 3) for v in at], "face": SIDE_FACE[side]}
    left = _cut(spans, c - length / 2 - GAP, c + length / 2 + GAP)
    return item, left


def _base_blocks(room: dict, sh: dict, pad: float) -> list:
    """The stairs, holes, pillars and the door openings as boxes (room-local), grown by pad."""
    out = [(b[0] - STAIR_GAP, b[1] - STAIR_GAP, b[2] + STAIR_GAP, b[3] + STAIR_GAP) for b in sh["stairs"] + sh["holes"]]
    for dr in sh["doors"]:
        x, z = dr["at"]
        r = dr["clear"] / 2 + pad
        out.append((x - r, z - r, x + r, z + r))
    return out


def room_clutter(level: dict, room: dict, dressing: dict, cat: dict, rule: dict) -> list[dict]:
    """The generated clutter items of one room (dressing without its block)."""
    rng = random.Random(f"{SEED}:{room['id']}")
    sh = hd.shell(level, room, LEVELS or [level])
    w, d = sh["w"], sh["d"]
    res = []
    for kind, it in hd.items(dressing):
        r = hd.resolve(it, cat)
        r["fp"] = hd.footprint(r)
        r["span"] = hd.span(r)
        r["kind"] = kind
        res.append(r)
    out: list[dict] = []
    # surfaces
    placed_on = 0
    used: dict = {}
    for host in res:
        kinds = HOSTS.get(host["id"])
        if not kinds or host.get("station") or host["kind"] != "props" or placed_on >= PER_ROOM:
            continue
        top = host["span"][1]
        hx0, hz0, hx1, hz1 = host["fp"]
        taken = [r["fp"] for r in res if r is not host and abs(r["span"][0] - top) < 0.06 and _ov(r["fp"], host["fp"])]
        cells = [(hx0 + GAP + i * 0.05, hz0 + GAP + j * 0.05)
                 for i in range(int((hx1 - hx0) / 0.05) + 1) for j in range(int((hz1 - hz0) / 0.05) + 1)]
        rng.shuffle(cells)
        n = min(PER_HOST, max(1, int((hx1 - hx0) * (hz1 - hz0) / 0.15)))
        face = next((f for f, y in hd.FACES.items() if abs(y - host["yaw"]) < 1e-6), "S")
        for _ in range(n):
            least = min(used.get(k, 0) for k in kinds)  # the room's least used kind of the host's: variety
            kind = rng.choice([k for k in kinds if used.get(k, 0) == least])
            b = _box(kind, (0, 0, 0), face, cat)
            for cx, cz in cells:
                bw, bd = b["fp"][2] - b["fp"][0], b["fp"][3] - b["fp"][1]
                x, z = round(cx + bw / 2, 2), round(cz + bd / 2, 2)
                fp = (x - bw / 2, z - bd / 2, x + bw / 2, z + bd / 2)
                if fp[2] > hx1 - GAP or fp[3] > hz1 - GAP or any(_ov(fp, t, GAP) for t in taken):
                    continue
                item = {"id": kind, "at": [x, round(top, 3), z], "face": face}
                out.append(item)
                taken.append(fp)
                placed_on += 1
                used[kind] = used.get(kind, 0) + 1
                break
    # walls
    near = 0.45
    wall_blocks = _base_blocks(room, sh, 0.1)
    for s in room.get("windows", []):
        wall_blocks.append((s[0] - WINDOW_HALF, s[1] - WINDOW_HALF, s[0] + WINDOW_HALF, s[1] + WINDOW_HALF))
    spans = {}
    for kind in rule.get("wall", ()):
        L, W, H = cat[kind]["size"]
        h0 = WALL_H[kind]
        blocks = wall_blocks + [b for b in _occupied(res, out, cat, h0 - 0.15, h0 + H + 0.15)]
        order = sorted("NSWE", key=lambda s: -sum(b - a for a, b in free_spans(sh, s, near, blocks)))
        for side in order:
            got = _place_along(sh, side, kind, L, 0.0, h0, free_spans(sh, side, near, blocks), rng, cat)
            if got:
                out.append(got[0])
                break
    # floor
    floor_blocks = _base_blocks(room, sh, 0.3)
    floor_blocks += room.get("legs", [])  # the routes' legs (house_routes), grown by the capsule's radius
    for m in room.get("stations", []):
        floor_blocks.append((m["at"][0] - 1, m["at"][2] - 1, m["at"][0] + 1, m["at"][2] + 1))
    for m in room.get("markers", []):
        if str(m.get("group", "")).startswith("spawn"):
            floor_blocks.append((m["at"][0] - 0.5, m["at"][2] - 0.5, m["at"][0] + 0.5, m["at"][2] + 0.5))
    for kind in rule.get("floor", ()):
        L, W, H = cat[kind]["size"]
        if kind == "doormat":
            if sh["doors"]:
                dr = sh["doors"][0]
                side, c = _side_of(dr["at"], w, d)
                if side:
                    off = hd.WALL_T + W / 2 + 0.05
                    x, z = dr["at"]
                    at = {"N": (x, 0, off), "S": (x, 0, d - off), "W": (off, 0, z), "E": (w - off, 0, z)}[side]
                    out.append({"id": kind, "at": [round(v, 3) for v in at], "face": SIDE_FACE[side]})
            continue
        blocks = floor_blocks + [b for b in _occupied(res, out, cat, 0.03, 0.35)]
        order = sorted("NSWE", key=lambda s: -sum(b - a for a, b in free_spans(sh, s, W + 0.2, blocks)))
        for side in order:
            got = _place_along(sh, side, kind, L, 0.05 + W / 2, 0, free_spans(sh, side, W + 0.2, blocks), rng, cat)
            if got:
                out.append(got[0])
                break
    return out


LEVELS: list = []  # every level, set by generate() (a room's shell sees the stairs of the levels around it)


def _occupied(res: list, out: list, cat: dict, lo: float, hi: float) -> list:
    """Footprints of the dressing's and the new items whose height span meets [lo, hi] (flat rugs skipped)."""
    boxes = []
    for r in res + [dict(_box(i["id"], i["at"], i.get("face", "S"), cat)) for i in out]:
        s = hd.span(r)
        if s[1] - s[0] > 0.03 and s[0] < hi and s[1] > lo:
            boxes.append(r["fp"])
    return boxes


def _windows(level: dict, room: dict) -> list:
    rx, ry, w, d = room["rect"]
    out = []
    for wdw in level.get("windows", []):
        x, y = wdw["at"][0] - rx, wdw["at"][1] - ry
        if _side_of((x, y), w, d)[0]:
            out.append((x, y))
    return out


def _legs(routes: dict, level: dict, room: dict) -> list:
    """Room-local boxes round the routes' legs on the room's level (each leg's bounding box grown by the radius)."""
    rx, ry = room["rect"][:2]
    pad = hd.RADIUS + 0.05
    out = []
    for r in routes.get("routes", []):
        pts = r["points"]
        for a, b in zip(pts, pts[1:]):
            if a[0] == b[0] == level["level"]:
                out.append((min(a[1], b[1]) - rx - pad, min(a[2], b[2]) - ry - pad,
                            max(a[1], b[1]) - rx + pad, max(a[2], b[2]) - ry + pad))
    return out


def _fmt_item(it: dict) -> str:
    lines = ["[[props]]", f'id = "{it["id"]}"', "at = [" + ", ".join(f"{v:g}" for v in it["at"]) + "]"]
    if "face" in it:
        lines.append(f'face = "{it["face"]}"')
    return "\n".join(lines)


def block(items: list[dict]) -> str:
    return MARK + "\n\n" + "\n\n".join(_fmt_item(i) for i in items) + "\n"


def generate(data: dict, folder: Path, cat: dict) -> dict:
    """room id -> (file path, the new file text, the clutter items) for every room in RULES that has a dressing file."""
    LEVELS[:] = data["levels"]
    texts = {f: f.read_text(encoding="utf-8") for f in sorted(Path(folder).glob("*.toml"))}
    routes = house_routes.load(Path(folder).parent)
    out = {}
    for lv in data["levels"]:
        for room in lv["rooms"]:
            rule = RULES.get(room["id"])
            path = Path(folder) / f"{room['id']}.toml"
            if not rule or path not in texts:
                continue
            base = strip(texts[path])
            dressing = tomllib.loads(base)
            rm = dict(room, windows=_windows(lv, room), legs=_legs(routes, lv, room))
            items = room_clutter(lv, rm, dressing, cat, rule)
            out[room["id"]] = (path, base + "\n" + block(items), items)
    return out


def write(data: dict, folder: Path, cat: dict) -> dict:
    """Writes every generated block; returns room id -> its clutter item count."""
    counts = {}
    for rid, (path, text, items) in generate(data, folder, cat).items():
        path.write_text(text, encoding="utf-8", newline="\n")
        counts[rid] = len(items)
    return counts
